### ISSUE TITLE
Split imports into multiple files for faster importing

### ISSUE THREAD

**Issue by toothrot** [kitchensurfing/postgres_to_redshift#7]
see http://docs.aws.amazon.com/redshift/latest/dg/t_splitting-data-files.html

**Comment by ashawley** [comment]
According to the AWS docs you reference,

> If you intend to use object prefixes to identify the load files, name each file with a common prefix. For example, the venue.txt file might be split into four files, as follows:
> 
> ```
> venue.txt.1
> venue.txt.2
> venue.txt.3
> venue.txt.4
> ```
> If you put multiple files in a folder in your bucket, you can specify the folder name as the prefix and COPY will load all of the files in the folder. If you explicitly list the files to be loaded by using a manifest file, the files can reside in different buckets or folders.

from:
http://docs.aws.amazon.com/redshift/latest/dg/t_splitting-data-files.html

It's not clear if Redshift absolutely needs to have an S3 folder for each table.  There is an example:

> Before uploading the file to Amazon S3, split the file into multiple files so that the COPY command can load it using parallel processing. The number of files should be a multiple of the number of slices in your cluster. Split your load data files so that the files are about equal size, between 1 MB and 1 GB after compression. For more information, see Splitting Your Data into Multiple Files.
> 
> For example, the venue.txt file might be split into four files, as follows:
> 
> ```
> venue.txt.1
> venue.txt.2
> venue.txt.3
> venue.txt.4
> ```
> The following COPY command loads the VENUE table using the pipe-delimited data in the data files with the prefix 'venue' in the Amazon S3 bucket mybucket.
> 
> 
> ```
> copy venue from 's3://mybucket/venue'
> credentials '<aws-auth-args>'
> delimiter '|';
> ```
> If no Amazon S3 objects with the key prefix 'venue' exist, the load fails.
> 

from: 
http://docs.aws.amazon.com/redshift/latest/dg/t_loading-tables-from-s3.html
